### ISSUE TITLE
用了这个主题后，无法全屏，感觉浪费了大屏幕

### ISSUE THREAD

**Issue by seekdoor** [DIYgod/ttrss-theme-rsshub#2]
<img width="1464" alt="Snipaste_2019-11-30_21-09-40" src="https://user-images.githubusercontent.com/6291329/69900986-cd253f00-13b5-11ea-80bb-efa86841392d.png">

系统MAC
分辨率 2k，开启了hiDPI，为1080p

**Comment by Rainshaw** [comment]
在设置中，先启用这个主题，然后点击自定义，粘贴下面的css代码进去保存
```css
body.ttrss_main #main{
width:auto;
}
```
