### ISSUE TITLE
BUG 为什么这个主题所有文字都在前面展示英文，选择语言无法隐藏前面的英文

### ISSUE THREAD

**Issue by guicaiyue** [DIYgod/ttrss-theme-rsshub#5]
![image](https://github.com/DIYgod/ttrss-theme-rsshub/assets/43875377/6bf4b803-975c-4daf-8f8f-951d7a65a9e0)

如题，是ttrss版本太新了导致，还是要有什么其它配置，怎么和网上其它人的如此不同

**Comment by p3psi-boo** [comment]
字体加载的问题，在 css 里面查找 @font-face，尝试修改成：

```css
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url('https://fastly.jsdelivr.net/npm/material-icon-font@3.0.1/iconfont/MaterialIcons-Regular.eot');
  /* For IE6-8 */
  src: local('Material Icons'), local('MaterialIcons-Regular'), url('https://fastly.jsdelivr.net/npm/material-icon-font@3.0.1/iconfont/MaterialIcons-Regular.woff2') format('woff2'), url('https://fastly.jsdelivr.net/npm/material-icon-font@3.0.1/iconfont/MaterialIcons-Regular.woff') format('woff'), url('https://fastly.jsdelivr.net/npm/material-icon-font@3.0.1/iconfont/MaterialIcons-Regular.ttf') format('truetype');
}
```
